# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
warnings_are_errors: false
cache: packages

before_install:
  - sudo $(which R) CMD javareconf
  - sudo add-apt-repository ppa:ubuntugis/ppa --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev

after_success:
  - Rscript -e 'covr::codecov()'
